# 18 jobs 
sweep:
  - device_train_microbatch_size: 32
    global_train_batch_size: 256
    num_passes: 1
    wandb:
      group: debug 
    optimizer:
      name: rotatedadamw 
      learning_rate: 1.0e-3
      beta_0: 0.9 
      beta_1: 0.95
      eps: 1.0e-8
      decouple_weight_decay: false
      weight_decay: 0.0
      decay_norm_and_bias: true
      decay_embeddings: true
      metrics_log_interval: 100
    scheduler:
      name: "cosine_with_warmup"
      t_warmup: 125
    max_duration: 1250 # 256 * 1024 * 12500 = 
    stop_at: 1250
